CREATE TABLE IF NOT EXISTS Student(
    Student_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Student_Name VARCHAR(30) UNIQUE

);

CREATE TABLE IF NOT EXISTS Course(
    Course_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Course_Name VARCHAR(30)

);

CREATE TABLE IF NOT EXISTS Project(
    Project_Name VARCHAR(30) PRIMARY KEY

);

CREATE TABLE IF NOT EXISTS Exam(
    Exam_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY

);

CREATE TABLE IF NOT EXISTS HandIn(
    HandIn_Name VARCHAR(30) NOT NULL,
    APPROVED VARCHAR(3)

);

CREATE TABLE IF NOT EXISTS Teacher(
    Teacher_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Teacher_Name VARCHAR(30) UNIQUE

);

CREATE TABLE IF NOT EXISTS Supervisor(
    REFERENCES Teacher(Teacher_id, Teacher_Name)
);
